name: "GitHub Actions CI"
on:
  push:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
  schedule:
    - cron: "0 5 * * SAT"
jobs:
  test-swift-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: swift test --parallel
